### ISSUE TITLE
Can't sign up as a new user 

### ISSUE THREAD

**Issue by ndorfin** [nzpug/chat#36]
I've tried several times now with different browser settings, but I can't register as a new user.

Steps to reproduce:

1. Go to https://chat.python.nz
2. Redirected to https://riot.python.nz/#/welcome
3. Click create account
4. Enter username, password, email.
5. Click Register
6. A `POST` to the register endpoint returns a 401
7. The Recaptcha Dialog displays briefly, and is gone before I can interact with it
8. The reigster form is shown again, but this time with an error:

<img width="455" alt="Screen Shot 2021-07-27 at 7 05 30 PM" src="https://user-images.githubusercontent.com/107569/127110966-fa82257b-bd7a-4351-ba3a-914e2ce463e1.png">

There are network errors for the `requestToken`, `register`, and `anchor` endpoints.

I then try log in, and that fails due to `Incorrect username and/or password.`

When I try use the Forgotten password form, it says my email has not been registered.

Isn't JavaScript amazing?

**Comment by iokiwi** [comment]
Hi @ndorfin,

Thanks for reaching out. I just saw your issue and I am looking into it. I will update you as soon as I can.

Regards,
Simon

**Comment by iokiwi** [comment]
Hi @ndorfin 

I have fixed the issue. You should be able to finish the account creation / password reset workflow now.

FWIW Google turned off 'Less secure app access' for the SMTP account due to inactivity. Really annoying but happens from time to time.  It's just due to the fact that google SMTP servers are not intended to be used in this way (its a feature not a bug)

My sincerest apologies for the delay. I will let you know that we are currently migrating from matrix to slack due to the fact that no one on the committee really has the bandwidth to maintain this matrix server to the level it deserves (As evidenced by your extended wait time - again I am sorry)

Feel free to make the most of the server in the meantime, and we will likely distribute an invitation to you to join the slack as soon as it is ready.

Regards,
Simon

**Comment by ndorfin** [comment]
Thanks @iokiwi
